### ISSUE TITLE
Unexpected left/right side collisions when walking on ground made of consecutive objects (Arcade Physics)

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2344] opened 2022-06-06 22:52 UTC
When walking along a ground made of consecutive objects with colliders, sometimes a left/right collision will occur. 

I remember seeing an issue/discussion somewhere (I cannot find it again for the life of me) where someone mentioned it's best to have larger, single bodies rather than consecutive. However, I am using the [tiled plugin](https://github.com/excaliburjs/excalibur-tiled#excalibur-wiring) with a "solid" layer for the ground, and I think it is laying out the colliders in similar fashion, leading to this behaviour.

### Steps to Reproduce

See this [CodeSandbox example](https://codesandbox.io/s/excalibur-side-collision-while-on-ground-8wf42u?file=/src/index.js). Move character left/right with arrow keys, jump with up. 

Open the dev console and walk the player along the lower ground. It will occasionally log "Left" or "Right" when the respective collision occurs. The higher ground is a single, large collider, while the bottom floor is individual 16x16 blocks. The behaviour should only happen on the lower ground.

### Expected Result

It occasionally triggers a collision on the left/right side

### Actual Result

It should not trigger any left/side collisions

### Environment

- browsers and versions: Chrome 102, Safari 15.5 
- operating system: macOS 12.4 
- Excalibur versions: 0.26, 0.25, didn't try anything earlier 
- Using a macbook pro with 120hz screen incase that has an impact on the physics tick rate

**Comment by eonarheim** [comment] 2022-06-06 23:50
@mattjennings thanks for the issue! This is a tricky one for sure!

I suspect the issue is the collision contact ordering, In the TileMap example there would be a pair for each tile overlapping with the player. There is currently no preferred order for pair resolution, for example if a contact that is close to a left/right edge of the player (which has a minimum translation distance horizontally smaller than the vertical) is picked first and resolved then it would present this behavior and fire a Left/Right collision. 

In an ideal platformer simulation resolving all vertical mtv's first, then any leftover horizontal would theoretically fix the issue.

I wonder if the fix is picking a preferred resolution direction for physics and/or perhaps a specific ordering of contact resolution? 
* Make a configurable resolution bias, something like `HorizontalThenVertical`, `VerticalThenHorizontal`
* Sort contacts by the bias and perform resolution as normal?
* Maybe a general solution is sorting pairs/contacts by their distance from each body in the pair?

I'll have to dig in a little deeper but I think some combination of these factors might also explain #2343 to some degree... I'll have some time this week to investigate.

**Comment by eonarheim** [comment] 2022-06-07 14:10
@mattjennings I think I've made some progress with the sorting by bias as a solution, I've also tweaked the arcade solver to solve position/velocity for a contact at once instead of solving all velocity then solving all position. 

Seems to fix this issue, but needs some more testing and work to make it configurable

https://github.com/excaliburjs/Excalibur/pull/2345

**Comment by mattjennings** [comment] 2022-06-07 15:27
oh wow! very much appreciate you looking into this so quickly - this looks promising!

**Closed** 2022-06-10 13:25 UTC
Labels: bug, system:physics
