### ISSUE TITLE
If the opacity of an Actor's drawing/color is 0, don't draw the actor

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#875] opened 2017-08-16 02:29 UTC
### Context
If an Actor's `currentDrawing` or `color` has it's opacity set to 0, the Actor will still draw transparent pixels to the canvas.

### Proposal
Set `Actor.visible` to false if the Actor's drawing or color is 100% transparent, to prevent transparent pixels from being drawn.

**Comment by tskull01** [comment] 2019-01-08 16:39
I would like to handle this.

**Comment by eonarheim** [comment] 2019-01-08 22:10
@tskull01 Go for it, I recommend refactoring visible to a getter/setter pair and implementing the logic in the setter.

**Comment by eonarheim** [comment] 2019-01-18 02:07
@tskull01 let me know if you would like any assistance

**Comment by DProBoy** [comment] 2019-08-06 17:12
@eonarheim Can i handle this issue ?

**Comment by SirKitboard** [comment] 2019-10-04 15:31
Is this issue still open?
I see that there were commits related to it but the issue is marked as openn

**Comment by eonarheim** [comment] 2019-10-04 15:42
@SirKitboard It is! All yours! 

There are a couple approaches, hooking into the internal [_postupdate](https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Actor.ts#L1544) and checking the Actor's color opacity then setting visible or not may make the most sense.

**Closed** 2019-10-08 22:27 UTC
Labels: Hacktoberfest, good first issue, optimization
