### ISSUE TITLE
Error: Cannot build new ExcaliburGraphicsContext2D

### ISSUE THREAD

**Issue by dosfx** [excaliburjs/Excalibur#3215] opened 2024-09-22 19:05 UTC
### Steps to Reproduce

Made a simple application:

```js
import { Engine} from "excalibur";

const game = new Engine({
    width: 600,
    height: 600,
});

game.start();
```
Packaged and served with parcel.

### Expected Result

Load the page and see the blue square

### Actual Result

Don't even get the blue square in my mobile browser. Attached to USB I can see in the console:
```
[Warn] :  Excalibur could not load webgl for some reason (Could not compile fragment shader:

ERROR: Expression too complex.


Source:
1: #version 300 es
2: precision mediump float;
...many more lines
Uncaught Error: Cannot build new ExcaliburGraphicsContext2D for some reason!
    at new ExcaliburGraphicsContext2DCanvas (ExcaliburGraphicsContext2DCanvas.ts:146:13)
    at new Engine (Engine.ts:908:30)
    at gNOv5.excalibur (test.ts:3:14)
    at newRequire (index.90abf92b.js:71:24)
    at index.90abf92b.js:122:5
    at index.90abf92b.js:145:3
```

### Environment

- browsers and versions: Brave Mobile (128.0.6613.127) Chrome Mobile (128.0.6613.146
- operating system: Android 14
- Excalibur versions: v0.29.3
Works fine in desktop browsers

### Current Workaround

Works if I do `Flags.useCanvasGraphicsContext();` from: https://excaliburjs.com/docs/graphics-context/#canvas-support

**Comment by eonarheim** [comment] 2024-09-22 19:30
@dosfx Wild! Thanks for the bug, can you share the hardware you're on too? 

I might be able to reproduce it in BrowserStack

**Comment by dosfx** [comment] 2024-09-22 19:32
Samsung Galaxy A53 5G cheers!

**Comment by eonarheim** [comment] 2024-09-22 19:37
@dosfx I think I have a lead on this, turns out certain hardware has a max shader sizes! 🤯 

I spotted a similar issue in pixi, theoretically should be a quick fix

**Comment by eonarheim** [comment] 2024-09-22 19:42
Digging in this looks like a maximum number of branches in the shader program (if statements)

**Comment by eonarheim** [comment] 2024-09-22 19:52
I found a device in BrowserStack I can reproduce, they don't have that exact combo but this seems to be the issue.

![image](https://github.com/user-attachments/assets/541df195-2d41-4cdb-b6d2-82fa905f8719)

**Comment by dosfx** [comment] 2024-09-22 19:59
That warning I copied in was basically all if statements, so that fits XD Sorry I should have grabbed more. I can hook it all back up again if you'd like and grab the whole thing.

**Comment by eonarheim** [comment] 2024-09-23 14:51
@dosfx Merged to main! Should be deployed to alpha bits momentarily

**Closed** 2024-09-23 14:50 UTC
Labels: bug

**Comment by dosfx** [comment] 2024-09-24 00:22
Confirmed works on my phone! :D
