### ISSUE TITLE
Error when enabling pointer capture on UIActor

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#746] opened 2017-01-23 23:36 UTC
### Steps to Reproduce

```typescript
class Button extends ex.Actor {

    private _func: () => void;

    constructor(x: number, y: number, width: number, height: number, color: ex.Color, func: () => void) {
        super(x, y, width, height);
        this.color = color;
        this._func = func;
    }

    public onInitialize(engine: ex.Engine) {
        this.on('pointerup', (event) => {
            this._func();
        });
    }
}

var button= new Button(500, 100, 100, 50, ex.Color.Red, () => {
    ex.Logger.getInstance().info('button clicked');
});
game.add(button);
```

### Expected Result

When the button is clicked, a log message appears in the console.

### Actual Result

An error is thrown:
excalibur-0.8.0.js:8458 [Fatal] :  TypeError: Cannot read property 'worldToScreenCoordinates' of undefined
    at Button.UIActor.contains (excalibur-0.8.0.js:10417)
    at Pointers.propogate (excalibur-0.8.0.js:12116)
    at CapturePointer.update (excalibur-0.8.0.js:2406)
    at Button.Actor.update (excalibur-0.8.0.js:8130)
    at Scene.update (excalibur-0.8.0.js:6911)
    at Engine._update (excalibur-0.8.0.js:13347)
    at mainloop (excalibur-0.8.0.js:13460)

#### Notes 
If the Button is changed to extend `ex.Actor` instead of `ex.UIActor`, this problem does not appear and the Button operates as expected.

Also, if a UIActor is used directly, the issue is not present:
```typescript
var button = new ex.UIActor(500, 500, 100, 50);
button.color = ex.Color.Green;
button.on('pointerup', (event) => {
            ex.Logger.getInstance().info('button clicked')
        });
game.add(button);
```

### Environment

- browsers: Chrome (55.0.2883.87), Firefox (50.1.0)
- operating systems: Windows 7
- Excalibur versions: 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.0-alpha.1275

**Comment by kamranayub** [comment] 2017-01-24 00:37
Can you try adding `super.initialize(engine)` in the `onInitialize` call? May be duplicate of #224

**Comment by jedeen** [comment] 2017-01-24 02:07
Yep, that solves the issue.

**Closed** 2017-01-24 02:07 UTC
Labels: bug, duplicate
