### ISSUE TITLE
Implement ray casting feature in Excalibur

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#232] opened 2014-03-21 17:12 UTC
This would be a neat feature to have, and could be useful in dynamic lighting effects like http://ncase.github.io/sight-and-light/

**Comment by jedeen** [comment] 2017-06-13 01:45
duplicate of https://github.com/excaliburjs/Excalibur/issues/665

**Closed by jedeen** 2017-06-13 01:45 UTC
Labels: duplicate
