### ISSUE TITLE
Code examples on website are shown in light and dark mode always

### ISSUE THREAD

**Issue by uvd540** [excaliburjs/Excalibur#2981] opened 2024-03-25 15:42 UTC
### Steps to Reproduce
1. Open Firefox (maybe other browsers too?).
2. View any of the documentation pages. For example, the [Hello World](https://excaliburjs.com/docs/getting-started) example.
3. Toggle dark mode on/off. In either case, each code example is shown in both light and dark modes.
![image](https://github.com/excaliburjs/Excalibur/assets/19933462/65a877bc-8bb6-4c35-a110-444a6d4167b2)

### Expected Result
Only see the light/dark code examples based on dark mode preference

### Actual Result
Seeing both code examples no matter what mode is selected

### Environment
- Firefox 115.9.1esr (64-bit)
- macOS 10.14
- Excalibur versions: Current

### Current Workaround
None

**Comment by eonarheim** [comment] 2024-03-26 00:03
@uvd540 Thanks for the bug! Very interesting I'm not able to repro on FF 124.0.1 on windows.

I'll do a little digging on what's going on, possibly a bug in FF?

What does Chrome/Safari show for you?

**Comment by uvd540** [comment] 2024-03-27 00:44
I'm seeing the same issue on Safari as well.
![image](https://github.com/excaliburjs/Excalibur/assets/19933462/4de4b2d7-8281-4aa5-bbce-2d9e22b6207a)

**Comment by eonarheim** [comment] 2024-03-28 02:45
I can reproduce it on browserstack with:
 
* Mojave/Safari 12
* Catalina/Safari 13
* BigSur/Safari 14

![image](https://github.com/excaliburjs/Excalibur/assets/612071/f1513d3a-8b74-47dd-862c-db9f89dee131)

Things only appear to work as intended at Monterey/Safari 15

I think it relates to this pseudo class selector using a `:has()` which isn't supported until Safari 15.4 and Firefox 121 https://caniuse.com/css-has.
![image](https://github.com/excaliburjs/Excalibur/assets/612071/7de566a3-5a51-489d-834a-c6b44f29504e)

This feature comes pre-bundled with Docusaurus v3 which we use for documentation, I'll see if their issue tracker has anything relating to this.

@kamranayub any ideas?

**Comment by eonarheim** [comment] 2024-03-28 02:50
It looks like we've fallen off the older safari support by default in browserlist

https://docusaurus.io/docs/browser-support

```
❯ npx browserslist --env="production"
Need to install the following packages:
  browserslist@4.23.0
Ok to proceed? (y) y
and_chr 122
and_ff 123
and_qq 14.9
and_uc 15.5
android 122
chrome 122
chrome 121
chrome 120
chrome 119
chrome 109
edge 122
edge 121
firefox 123
firefox 122
firefox 115
ios_saf 17.4
ios_saf 17.3
ios_saf 17.2
ios_saf 17.1
ios_saf 16.6-16.7
ios_saf 16.1
ios_saf 15.6-15.8
kaios 3.0-3.1
kaios 2.5
op_mini all
op_mob 80
opera 108
opera 107
opera 106
safari 17.4
safari 17.3
safari 17.2
samsung 23
samsung 22
```

**Comment by eonarheim** [comment] 2024-04-25 13:21
@uvd540 @mattjennings I've opened an issue against docusaurus for this https://github.com/facebook/docusaurus/issues/10074

I'm going to close this issue as wont fix for now.

**Closed by eonarheim** 2024-04-25 13:21 UTC
Labels: bug
